# Add 'backend' label to any change within src/ but not web* folders
'backend':
  - any: ['src/**/*', '!src/web/**/*', '!src/webSvelte/**/*', '!src/webClientLib/**/*']

# Add 'frontend' label to any change to webSvelte folder
'frontend':
  - any: ['src/webSvelte/**/*']

# Add 'client lib' label to any change to webClientLib folders
'client lib':
  - any: ['src/webClientLib/**/*']
