<script lang="ts">
  import {Tag} from 'carbon-components-svelte';
  import {AssemblyCluster} from 'carbon-icons-svelte';
  import HoverTooltip from '../common/HoverTooltip.svelte';

  export let embedding: string | undefined;
  export let hideEmbeddingName = false;
</script>

<div class="embedding-badge" class:embedding-badge-nolabel={hideEmbeddingName}>
  <Tag {...$$restProps} type="purple">
    <HoverTooltip
      size="small"
      icon={AssemblyCluster}
      triggerText={!hideEmbeddingName ? embedding : ''}
    >
      This field was generated by an embedding.
    </HoverTooltip>
  </Tag>
</div>

<style lang="postcss">
  :global(.embedding-badge-nolabel .bx--tooltip__label .bx--tooltip__trigger) {
    @apply m-0;
  }
</style>
