<script lang="ts">
  import {Tag} from 'carbon-components-svelte';
  import {EdgeCluster, View} from 'carbon-icons-svelte';
  import {hoverTooltip} from '../common/HoverTooltip';

  export let isPreview = false;

  const tooltipText = isPreview
    ? 'Signal is in preview mode and has not been computed for the whole dataset.'
    : 'This field was generated by a signal.';
  const icon = isPreview ? View : EdgeCluster;
</script>

<div class="signal-badge" use:hoverTooltip={{tooltipText}}>
  <Tag {...$$restProps} type={isPreview ? 'green' : 'blue'} {icon} />
</div>

<style lang="postcss">
  :global(.signal-badge .bx--tag) {
    @apply px-2;
  }
  :global(.signal-badge .bx--tag__custom-icon) {
    @apply mr-0;
  }
  :global(.signal-badge .bx--tooltip__label .bx--tooltip__trigger) {
    @apply m-0;
  }
</style>
