<script lang="ts">
  import {Tag} from 'carbon-components-svelte';
  import {EdgeCluster, View} from 'carbon-icons-svelte';
  import HoverTooltip from '../common/HoverTooltip.svelte';

  export let isPreview = false;
</script>

<div class="signal-badge">
  {#if isPreview}
    <Tag {...$$restProps} type="green">
      <HoverTooltip size="small" icon={View}>
        Signal is in preview mode and has not been computed for the whole dataset.
      </HoverTooltip>
    </Tag>
  {:else}
    <Tag {...$$restProps} type="blue">
      <HoverTooltip size="small" icon={EdgeCluster}>
        This field was generated by a signal.
      </HoverTooltip>
    </Tag>
  {/if}
</div>

<style lang="postcss">
  :global(.signal-badge .bx--tag) {
    @apply px-2;
  }
  :global(.signal-badge .bx--tag__custom-icon) {
    @apply mr-0;
  }
  :global(.signal-badge .bx--tooltip__label .bx--tooltip__trigger) {
    @apply m-0;
  }
</style>
